### ISSUE TITLE
Realms get closed prematurely with ROS 2.8.0

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-graphql-service#39]
Reported in #35, a user is seeing this happen sporadically:

```
Error: Cannot access realm that has been closed.
0|npm      |     at queryResolver.(anonymous function) (/home/ubuntu/ros/node_modules/realm-graphql-service/dist/service.js:235:40)
0|npm      |     at resolveFieldValueOrError (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:498:12)
0|npm      |     at resolveField (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:462:16)
0|npm      |     at /home/ubuntu/ros/node_modules/graphql/execution/execute.js:311:18
0|npm      |     at Array.reduce (<anonymous>)
0|npm      |     at executeFields (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:308:42)
0|npm      |     at executeOperation (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:236:122)
0|npm      |     at executeImpl (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:133:26)
0|npm      |     at Object.execute (/home/ubuntu/ros/node_modules/graphql/execution/execute.js:110:229)
0|npm      |     at doRunQuery (/home/ubuntu/ros/node_modules/apollo-server-core/dist/runQuery.js:98:42)
```

Because of the Realm cache, this means they'll get a closed Realm on subsequent requests as well until the Realm is evicted from the cache. It appears the issue manifests after upgrading from 2.7.0 to 2.8.0.

**Comment by LucidComplex** [comment]
Hmm, I haven't tried refreshing GraphiQL, I'll try that when the issue comes up.

>  Also, just to make sure, you're accessing the same Realm from both, right?

Yes, I'm accessing the same realm. Other realms stay available for access.

**Comment by LucidComplex** [comment]
The issue has come up. This time, GraphiQL stops working. Regular HTTP POSTs to the GraphQL endpoint don't work as well, but requests with `realm-graphql-client` work. It appears that GraphQL/POST and `realm-graphql-client` experience the realm being closed separately.

**Comment by LucidComplex** [comment]
We're at ROS 3 now, Realm still closes.

**Comment by howdyhyber** [comment]
Is there any update regarding this issue?

**Comment by SogoGolf** [comment]
hi @nirinchev we saw this same issue today on our dev server. neither GraphiQL nor realm-graphql-client we're returning data and we're instead throwing the following error:

```
{
  "data": {
    "golfers": null
  },
  "errors": [
    {
      "message": "Cannot access realm that has been closed.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "golfers"
      ]
    }
  ]
}
```

**Dev server versions**
**realm-object-server** : ran ```ros --version``` and it displayed ```3.0.0```. However looking in the node_modules directory on the server I can see that the package.json is ```"version": "3.4.3"``` (maybe a bug with ros --version?).

**realm-graphql-service** version: ```"version": "2.3.2"```


The workaround was to re-start ROS on the dev server. Then GraphiQL and ```realm-graphql-client``` started to work again. However obviously this isn't acceptable for  production.

Happy to help debug on our side. This may mean nothing but at the time we experienced this issue there were ~ 130 open files in ROS (per the log in Realm Studio).

**Comment by astigsen** [comment]
@nirinchev: this issue relates to an old version of ROS. Can it be closed for now or is it still relevant?

**Comment by nirinchev** [comment]
I believe @kraenhansen has experienced it with a recent ROS version.

**Comment by kraenhansen** [comment]
Yep - I experienced this with ROS running in Realm Cloud about 3 weeks ago. I didn't get to make it reproducible, but I expect that it can happen if trying to open a GraphQL connection with an invalid access token.
