### ISSUE TITLE
GraphQL Internal Error

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#59]
We upgraded our server from 3.4.2 to 3.6.12, and we are experiencing some issue something like this.

Internal server error: Error: Field Query.taskTemplates can only be defined once. Field Mutation.deleteTaskTemplates can only be defined once. Field Subscription.taskTemplates can only be defined once. at assertValidSchema (/home/ubuntu/spingine/node_modules/graphql/type/validate.js:82:11) at Object.validate (/home/ubuntu/spingine/node_modules/graphql/validation/validate.js:58:35) at doRunQuery (/home/ubuntu/spingine/node_modules/apollo-server-core/dist/runQuery.js:110:38) at /home/ubuntu/spingine/node_modules/apollo-server-core/dist/runQuery.js:21:56 at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)

How do we solve this?

**Comment by nirinchev** [comment]
It appears as if the GraphQL service is creating duplicate definitions for the `TaskTemplate` class. Can you open this realm in Studio and verify that it doesn't have duplicate tables? If it doesn't, can you share the Realm file so we can examine it locally and try to reproduce?

**Comment by howdyhyber** [comment]
In our Realm Path, there is TaskTemplate Class, and there is TaskTemplates class.

**Comment by nirinchev** [comment]
Unfortunately nothing comes to mind - the assumption that classes are singular and PascalCase-d affects a lot of the schema generation code, so I don't think I can make a change without breaking every consumer.

It would be easiest if you could discard that Realm file and start from scratch. If that doesn't work for you (e.g. because it's used in production and there are users who depend on it), you could probably fork the GraphQL service and make the changes necessary to support your use case - e.g. if you don't use the `TaskTemplate` class anymore, you could filter it out in the schema generation code here:

https://github.com/realm/realm-graphql-service/blob/master/src/service.ts#L417

**Comment by howdyhyber** [comment]
How to do it?

**Comment by howdyhyber** [comment]
@nirinchev This solves our problem. Thanks :tada:
